import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/header";

export const metadata: Metadata = {
  title: "EPICURE",
  icons: {
    icon: '/assets/icons/epicure-icon.svg',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header/>
        {children}
        <h3>footer</h3>
      </body>
    </html>
  );
}
